### ISSUE TITLE
application crashed on Windows 7 32-bit SP1 - Microsoft NET Framework 4.6.1

### ISSUE THREAD

**Issue by yellow-panther** [furrysalamander/BreezeChess#2]
Microsoft NET Framework 4.6.1  https://www.microsoft.com/net/download/archives  
Problemereignisname:	APPCRASH
  Anwendungsname:	Breeze Chess Console.vshost.exe
  Anwendungsversion:	14.0.23107.0
  Anwendungszeitstempel:	559b788a
  Fehlermodulname:	KERNELBASE.dll
  Fehlermodulversion:	6.1.7601.17514
  Fehlermodulzeitstempel:	4ce7b8f0  Ausnahmecode:	e0434352
  Ausnahmecode:	e0434352
  Ausnahmeoffset:	0000b760
  Betriebsystemversion:	6.1.7601.2.1.0.256.48
  Gebietsschema-ID:	1031
  Zusatzinformation 1:	0a9e
  Zusatzinformation 2:	0a9e372d3b4ad19135b953a78882e789
  Zusatzinformation 3:	0a9e
  Zusatzinformation 4:	0a9e372d3b4ad19135b953a78882e789

**Comment by furrysalamander** [comment]
Is this the one that you're trying to run?
https://github.com/furrysalamander/BreezeChess/blob/master/Breeze%20Chess%20Console/bin/Release/Breeze%20Chess%20Console.exe

**Comment by yellow-panther** [comment]
Breeze Chess Console without the extension vshost works, but I try to launch the application Breeze Chess Console.vshost (into Debug and Release folder). Probably my mistake, but why are the Breeze Chess Console.vshost mentioned there, too?

**Comment by furrysalamander** [comment]
It's a file that visual studio generates.  When I uploaded this to GitHub, I just uploaded the whole project folder.
