### ISSUE TITLE
UCI compatibility

### ISSUE THREAD

**Issue by yellow-panther** [furrysalamander/BreezeChess#3]
How can the problem "embedding an UCI  compatible engine like Stockfish  https://stockfish.s3.amazonaws.com/stockfish-9-win.zip into BreezeChess" be accomplished? I cannot detect any manual with a step-by-step instruction on your website. Or is this a plan for the future?

**Comment by furrysalamander** [comment]
Breeze Chess *is* a UCI compatible engine, just like Stockfish.  You use both with a separate program, like Arena.

**Comment by yellow-panther** [comment]
Do you have plans to enhance Breeze Chess AI  in a way that it can be used with external UCI-engines e.g. Stockfish, Fire, Andscacs, Komodo like WinBoard Interface, ChessGUI, Scid vs PC or Arena?

**Comment by furrysalamander** [comment]
It already is Arena compatible.  I used arena when developing it, so you should be able to use arena to make it fight other engines.
