### ISSUE TITLE
any relationship of breeze Chess to CPW Engine?

### ISSUE THREAD

**Issue by yellow-panther** [furrysalamander/BreezeChess#4]
Hello,
cf. Günther´s contribution here: http://talkchess.com/forum3/viewtopic.php?f=2&t=68433

https://github.com/nescitus/cpw-engine - https://www.chessprogramming.org/CPW-Engine

**Comment by furrysalamander** [comment]
I studied the chess playing wiki when I was learning how chess playing AIs work.  I don't claim that this engine is anything new that people have never seen before.  A lot of the reason why I wrote this was that I wanted to learn how AI works and become a better program.
